# Generated by Django 2.2.2 on 2020-11-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0002_auto_20201102_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
